main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    # path('tips', tips, name='tips'),
]

post_pengumuman/urls.py
from django.urls import path
from . import views

app_name = 'post_pengumuman'

urlpatterns = [
    path('', views.home, name='home'),
    path('<string>/', views.form, name='form'),
    path('<string>/sukses', views.sukses, name='sukses'),
]

tk1_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('tips/',include('tips.urls')),
    path('post-pengumuman/', include('post_pengumuman.urls')),
    path('periksa/', include('periksa.urls')),
    
]

post_pengumuman/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Pemerintah(models.Model):
    PROVINSI_CHOICES = (
        ('BAN','Banten'),
        ('JKT','DKI Jakarta'),
        ('JBR','Jawa Barat'),
        ('JTE','Jawa Tengah'),
        ('YOG','DI Yogyakarta'),
        ('JTI','Jawa Timur'),
    )
    provinsi = models.CharField(
        max_length=3,
        choices= PROVINSI_CHOICES,
        default='JKT',
    )

    def __str__(self):
        return self.get_provinsi_display()

class Pengumuman(models.Model):
    PRIORITAS_CHOICES = (
        ('00','Urgent'),
        ('01','Tinggi'),
        ('02','Normal'),
        ('03','Rendah'),
    )
    judul = models.CharField(max_length = 50, blank=False)
    prioritas = models.CharField(
        max_length=2,
        choices= PRIORITAS_CHOICES,
        default='02',
    )
    pemerintah = models.ForeignKey("Pemerintah", default=None, on_delete=models.CASCADE)
    isi_pengumuman = models.TextField(blank=False)

    def __str__(self):
        return '{}-{}-{}'.format(self.judul[:15], self.get_prioritas_display(), str(self.pemerintah))
    
    class Meta:
        ordering = ['prioritas']
        unique_together = ['judul', 'prioritas', 'pemerintah']

post_pengumuman/forms.py
from django.forms import ModelForm, TextInput, Textarea
from .models import Pengumuman

class PengumumanForm(ModelForm):
    class Meta:
        model = Pengumuman
        fields = ['judul', 'prioritas', 'isi_pengumuman']
        widgets = {
            'judul': TextInput(attrs={'placeholder': 'contoh: DKI Jakarta - PSBB Diperpanjang'}),
        }

post_pengumuman/views.py
from django.contrib import messages
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from .models import Pengumuman, Pemerintah
from .forms import PengumumanForm

# Create your views here.
def home(request):
    return render(request, 'post_pengumuman/post_home.html')

def form(request, string):
    pemerintah_obj, created = Pemerintah.objects.get_or_create(provinsi = string)
    if request.method == 'POST':
        form = PengumumanForm(request.POST)
        if form.is_valid():
            pengumuman_obj = form.save(commit=False)
            pengumuman_obj.pemerintah = pemerintah_obj
            try:
                pengumuman_obj.save()
            except IntegrityError as e:
                messages.add_message(request, messages.ERROR, 'Gagal: Duplikat pengumuman dengan judul dan prioritas yang sama.')
                return HttpResponseRedirect('/post-pengumuman/{}/'.format(string))
            return HttpResponseRedirect('/post-pengumuman/{}/sukses'.format(string))
    else:
        form = PengumumanForm()
    return render(request, 'post_pengumuman/post_form.html', {'provinsi':str(pemerintah_obj), 'form':form, 'kode_prov':string})

def sukses(request, string):
    pemerintah = Pemerintah.objects.get(provinsi = string)
    message = 'Pengumuman untuk Provinsi {} berhasil ditambahkan. Kembali ke halaman utama untuk melihatnya.'.format(str(pemerintah))
    return render(request, 'post_pengumuman/post_home.html', {'message':message, 'provinsi':str(pemerintah), 'kode_prov':string})

post_pengumuman/templates/post_pengumuman/post_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'post_pengumuman/style.css' %}">
    <title>Buat Pengumuman - Risikovid</title>
{% endblock meta %}
{% block content %}
    </div></div>
    <div class="container">
        <div class="row justify-content-center py-1 px-5">
            {% if messages %}
            <ul class="messages my-0">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <div class="row justify-content-center py-5 mx-2">
            <h2 class="ubuntu text-center">Post Pengumuman</h2>
        </div>
        <div class="row justify-content-center pb-5 px-2">
            <form action="{% url 'post_pengumuman:form' kode_prov %}" method="POST">
                <h3 class="ubuntu pb-2">Pemerintah Provinsi {{provinsi}}</h3>
                {% csrf_token %}
                {{form}}
                <div>
                    <button type="submit">Kirim</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

post_pengumuman/templates/post_pengumuman/post_home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'post_pengumuman/style.css' %}">
    <title>Buat Pengumuman - Risikovid</title>
{% endblock meta %}
{% block content %}
    </div></div>
    <div class="container">
        <div class="row justify-content-center py-1 px-5">
            {% if message %}
            <div class="message">
                <p class="my-0">{{message}}</p>
            </div>
            {% endif %}
        </div>
        <div class="row text-center justify-content-center py-5 mx-1">
            <h2 class="ubuntu">Masuk sebagai Akun Pemerintah untuk Post Pengumuman</h2>
        </div>
        <div class="row justify-content-center px-4 pb-5">
            <div class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'BAN' %}">
                    <img src="{% static 'post_pengumuman/img/Banten.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>
            <div class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'JKT' %}">
                    <img src="{% static 'post_pengumuman/img/Jakarta.png' %}" class="thumbnail rounded img-fluid" >
                </a>
            </div>
            <div class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'JBR' %}">
                    <img src="{% static 'post_pengumuman/img/West_Java.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>
            <div class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'JTE' %}">
                    <img src="{% static 'post_pengumuman/img/Central_Java.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>
            <div class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'YOG' %}">
                    <img src="{% static 'post_pengumuman/img/Yogyakarta.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>
            <div class="col-xs-12 col-md-4 col-sm-6 text-center">
                <a href="{% url 'post_pengumuman:form' 'JTI' %}">
                    <img src="{% static 'post_pengumuman/img/East_Java.png' %}" class="thumbnail rounded img-fluid">
                </a>
            </div>

        </div>
    </div>
{% endblock content %}

post_pengumuman/templates/post_pengumuman/post_sukses.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'post_pengumuman/style.css' %}">
    <title>Buat Pengumuman - Risikovid</title>
{% endblock meta %}
{% block content %}
    <div class="container">
        <div class="message">
            <p>{{message}}</p>
        </div>
        <div class="thumbnails">
        {% if kode_prov == 'BAN'%}
            <img src="../../static/post_pengumuman/img/Banten.png">
        {% endif %}
        {% if kode_prov == 'JKT'%}
            <img src="../../static/post_pengumuman/img/Jakarta.png">
        {% endif %}
        {% if kode_prov == 'JBR'%}
            <img src="../../static/post_pengumuman/img/West_Java.png">
        {% endif %}
        {% if kode_prov == 'JTE'%}
            <img src="../../static/post_pengumuman/img/Central_Java.png">
        {% endif %}
        {% if kode_prov == 'YOG'%}
            <img src="../../static/post_pengumuman/img/Yogyakarta.png">
        {% endif %}
        {% if kode_prov == 'JTI'%}
            <img src="../../static/post_pengumuman/img/East_Java.png">
        {% endif %}
        </div>
    </div>
{% endblock content %}